import{S as h,a as b,i as m}from"./assets/vendor-Fd3mU3Z4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();let L=new h(".gallery a",{captionsData:"alt",captionDelay:250,enableKeyboard:!0,closeOnClick:!0,swipeClose:!0});function v(o,s){const i=o.map(t=>`<li>
            <div class="gallery">
                <a href="${t.largeImageURL}">
                    <img src="${t.largeImageURL}" alt="${t.tags}" title="${t.tags}"/>
                </a>
            </div>
            <div class="info">
                <p><b>Likes:</b> ${t.likes}</p>
                <p><b>Views:</b> ${t.views}</p>
                <p><b>Comments:</b> ${t.comments}</p>
                <p><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </li>`).join("");s.insertAdjacentHTML("beforeend",i),L.refresh()}async function g(o,s,i,t){const e="48820744-2d2f423ba9a206b8d884159e3",r="https://pixabay.com/api/";try{const n=await b.get(r,{params:{key:e,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:t}});return n.data.hits.length===0?(m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),0):(v(n.data.hits,s),n.data.totalHits)}catch(n){return console.log("Помилка при запиті:",n),0}}const y=document.querySelector(".form"),l=document.querySelector(".galleryList"),u=document.querySelector(".loader"),a=document.querySelector(".load-more");let c=1;const p=40;let f=0,d="";function w(){const o=l.querySelector("li");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}y.addEventListener("submit",async o=>{if(o.preventDefault(),l.innerHTML="",c=1,a.style.display="none",d=y.elements.text.value.trim(),d===""){m.error({title:"Error",message:"Поле пошуку не може бути порожнім!",position:"topCenter"});return}u.style.display="inline-block",f=await g(d,l,c,p),u.style.display="none",f>p&&(a.style.display="block",a.textContent="Load more",l.after(a)),y.reset()});a.addEventListener("click",async()=>{c+=1,u.style.display="inline-block",await g(d,l,c,p),u.style.display="none",w(),c*p>=f&&(a.style.display="none",m.info({title:"Info",message:"We are sorry, but you have reached the end of search results.",position:"topCenter"}))});
//# sourceMappingURL=index.js.map
